version: "3"
services:
  postgres:
    image: postgres:10.4-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "fizzbuzz"
      POSTGRES_PASSWORD: "fizzbuzz"
      POSTGRES_DB: "fizzbuzz"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  mysql:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_USER=fizzbuzz
      - MYSQL_PASSWORD=f1zzbuzz
      - MYSQL_DATABASE=fizzbuzz

  fizzbuzz-api:
    build: .
    depends_on:
      - mysql
    links:
      - mysql:mysql
    env_file:
      - .env
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - .:/fizzbuzz
    restart: always
    environment:
      FLASK_ENV: "production" 

volumes:
  postgres_data:
