version: "3"
services:
  mysql:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=fizzbuzz
      - MYSQL_PASSWORD=f1zzbuzz
      - MYSQL_DATABASE=fizzbuzz

  fizzbuzz:
    build: .
    depends_on:
      - mysql
    links:
      - mysql:mysql
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/fizzbuzz
    restart: always
    environment:
      FLASK_ENV: "production"
