version: "3"
services:
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd123
      MYSQL_DATABASE: fizzbuzz
    volumes:
      - /var/lib/mysql

  fizzbuzz:
    image: python:3.7
    links:
      - mysql
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/fizzbuzz
    restart: always
    environment:
      FLASK_ENV: "production"
    command: >
      bash -c "cd /fizzbuzz && 
      pip install -r requirements.txt && 
      flask db upgrade && 
      flask run"
